# The below program was generated by Microsoft CoPilot (03/09/2026, 11:27pm), based on the prompt:

# Situation: A small general practitioner clinic requires a simple system to store appointment schedules. The information stored for each scheduled appointment is: Patient Name, Practitioner Name, and Appointment Time (Date and time).
# Requirements: There will be no database or GUI, all of this is done within the console. The system only stores the specified information. The system is simplistic, requiring minimal programming knowledge to understand and use. The system will handle errors.
# You will program the system in Python based on the above requirements.



# The response from Microsoft CoPilot is:

# Here’s a clean, minimal, console‑based Python appointment system that meets your requirements: **no database, no GUI, simple logic, error handling, and easy for beginners to understand.**

# ---

# ## **Concise takeaway**
# You get a small Python program that:
# - Stores appointments in memory  
# - Lets users add and view appointments  
# - Validates input and handles errors  
# - Runs entirely in the console  

# ---

# ## **Complete Python Program (simple and beginner‑friendly)**

# ```python
# # ---------------------------------------------
# # Simple Appointment Booking System (Console)
# # ---------------------------------------------

appointments = []  # List to store all appointments


def book_appointment():
    """Create a new appointment with basic error handling."""
    print("\n--- Book a New Appointment ---")

    patient = input("Enter Patient Name: ").strip()
    practitioner = input("Enter Practitioner Name: ").strip()
    time = input("Enter Appointment Time (e.g., 2024-07-20 10:00 AM): ").strip()

    # Basic validation
    if not patient:
        print("Error: Patient name cannot be empty.")
        return
    if not practitioner:
        print("Error: Practitioner name cannot be empty.")
        return
    if not time:
        print("Error: Appointment time cannot be empty.")
        return

    # Store appointment
    appointment = {
        "patient": patient,
        "practitioner": practitioner,
        "time": time
    }
    appointments.append(appointment)
    print("Appointment booked successfully!")


def display_appointments():
    """Show all stored appointments."""
    print("\n--- All Appointments ---")
    if not appointments:
        print("No appointments recorded.")
        return

    for i, appt in enumerate(appointments, start=1):
        print(f"{i}. Patient: {appt['patient']} | Practitioner: {appt['practitioner']} | Time: {appt['time']}")


def main_menu():
    """Main menu loop."""
    while True:
        print("\n=== Clinic Appointment System ===")
        print("1. Book Appointment")
        print("2. View Appointments")
        print("3. Exit")

        choice = input("Choose an option (1-3): ").strip()

        if choice == "1":
            book_appointment()
        elif choice == "2":
            display_appointments()
        elif choice == "3":
            print("Exiting system. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")


# Start the program
main_menu()
# ```

# ---

# ## **How this meets your requirements**

# ### **✔ No database**
# Everything is stored in a simple Python list.

# ### **✔ No GUI**
# Runs entirely in the console.

# ### **✔ Stores only required information**
# Each appointment contains:
# - Patient Name  
# - Practitioner Name  
# - Appointment Time  

# ### **✔ Beginner‑friendly**
# - No advanced Python features  
# - Clear functions  
# - Simple menu loop  

# ### **✔ Error handling**
# - Empty input checks  
# - Invalid menu choice handling  

# ### **✔ Minimal but functional**
# Enough structure to be useful without overwhelming a beginner.

# ---

# If you want, I can help you extend this system with:
# - Time clash detection  
# - Saving appointments to a text/JSON file  
# - Searching appointments  
# - Editing or deleting appointments  

# Just tell me what direction you want to take next.